title: 编程和酒
url: https://mariosong.github.io
baseurl: ''
cdnurl: 'https://blog-biezhi-me-1251171175.cos.ap-shanghai.myqcloud.com'
description: >
  关于编程、人生、认知和思想。

permalink: /:year/:month/:title.html

image: /public/images/mountains.jpg
color: '#dc322f'
google_analytics: 
baidu_analytics: 2209f3e596f3e0c61a293f49a2f65ba3
disqus: blog-biezhi-me

markdown: kramdown
highlighter: rouge
paginate: 12
paginate_path: "/page/:num"

# 作者信息
author:
  name: biezhi
  email: biezhi.me@gmail.com
  photo: /public/images/avatar.jpeg

# 社交信息
socials:
  - title: Github
    icon: github
    url: https://github.com/MarioSong
  - title: Twitter
    icon: twitter
    url: https://twitter.com/MrMarioSong
  - title: Youtube
    icon: youtube
    url: '#'
  - title: Telegram Group
    icon: telegram
    url: https://telegram.me/github_cn

# 友链
links:
  - title: GitHub
    url: http://www.github.com/

# html 压缩
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  startings: [html, head, body]

# sass 解析
sass:
  sass_dir: public/css
  style: compressed

# 插件
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
